version: '3.1'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    tty: true
    env_file: ./env/nginx-proxy/.env
    volumes:
      - ./data/nginx-proxy/logs:/var/log/nginx
      - ./env/nginx-proxy/ssl/certs:/etc/nginx/certs
      - ./env/nginx-proxy/ssl/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem
      - ./env/nginx-proxy/share:/usr/share/nginx/html
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    restart: always
    tty: true
    env_file: ./env/letsencrypt/.env
    volumes:
      - ./data/nginx-proxy/logs:/var/log/nginx
      - ./env/nginx-proxy/ssl/certs:/etc/nginx/certs
      - ./env/nginx-proxy/ssl/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem
      - ./env/nginx-proxy/share:/usr/share/nginx/html
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: proxy-network