version: '3.1'

services:
  
  nr_nginx:
    container_name: nr_nginx
    build: ./env/nginx
    ports:
      - 8080:8080
    expose:
      - 80
      - 443
    env_file:
      - ./env/nginx/.env
    depends_on:
      - nr_php72
    tty: true
    volumes:
      - ./src:/home/www/naturalremedy/src
      - ./storage:/home/www/storage/naturalremedy
      - ./data/nginx/logs:/var/log/nginx
      - ./env/nginx/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./env/nginx/webserver/conf.d:/etc/nginx/conf.d
      - ./env/nginx/webserver/defaults:/etc/nginx/defaults
      - ./env/nginx/webserver/global:/etc/nginx/global
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nr_mysql:
    container_name: nr_mysql
    build: ./env/mysql
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql/.env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./env/mysql/conf.d:/etc/mysql/conf.d
      - ./data/dbimport/:/docker-entrypoint-initdb.d

  nr_elasticsearch:
    build: ./env/elasticsearch
    container_name: nr_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    tty: true
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  nr_mailhog:
    image: mailhog/mailhog:latest
    container_name: nr_mailhog
    ports:
      - 8025:8025
    depends_on:
      - nr_php72

  nr_redis:
    image: redis:4-alpine
    container_name: nr_redis
    command: /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./env/redis:/usr/local/etc/redis

  nr_php72:
    container_name: nr_php72
    build: ./env/php72
    hostname: php72
    depends_on:
      - nr_mysql
    ports:
      - 9000:9000
      - 3000:3000
    volumes:
      - ./env/composer:/home/www/.composer
      - ./env/global/bashrc:/home/www/.bashrc
      - ./data/bash/.bash_history:/home/www/.bash_history
      - ~/.ssh:/home/www/.ssh:ro
      - ~/.gitconfig:/home/www/.gitconfig:ro
      - ./storage:/home/www/storage/naturalremedy
      - ./src:/home/www/naturalremedy/src

networks:
  default:
    external:
      name: nginx-proxy