version: '3.1'

services:
  mysql:
    container_name: mysql
    build: ./env/mysql
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql/.env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./env/mysql/conf.d:/etc/mysql/conf.d
      - ./data/dbimport/:/docker-entrypoint-initdb.d

  elasticsearch:
    build: ./env/elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    tty: true
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 8025:8025
    depends_on:
      - webapp

  redis:
    image: redis:4-alpine
    container_name: redis
    command: /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./env/redis:/usr/local/etc/redis

  webapp:
    container_name: webapp
    build: ./env/webapp
    hostname: webapp
    depends_on:
      - mysql
    ports:
      - 9000:9000
      - 80
      - 443
    env_file: ./env/webapp/.env
    environment:
      - VIRTUAL_HOST=naturalremedy.portchris.co.uk
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy-network
    volumes:
      - ./env/composer:/home/www/.composer
      - ./env/global/bashrc:/home/www/.bashrc
      - ./data/bash/.bash_history:/home/www/.bash_history
      - ~/.ssh:/home/www/.ssh:ro
      - ~/.gitconfig:/home/www/.gitconfig:ro
      - ./storage:/home/www/storage/naturalremedy
      - ./src:/home/www/naturalremedy/src
      - ./env/webapp/config/nginx/webserver/conf.d:/etc/nginx/conf.d
networks:
  default:
    external:
      name: proxy-network